sylius_grid:
  grids:
    smartarget_smartarget_whatsapp_contact_us:
      driver:
        name: doctrine/orm
        options:
          class: Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Entity\Message
      limits: [25, 50, 100, 200]
      fields:
        phoneNumber:
          type: string
          label: smartarget_smartarget_whatsapp_contact_us.ui.form.phoneNumber
        smartargetUserId:
          type: string
          label: smartarget_smartarget_whatsapp_contact_us.ui.form.smartargetUserId
        enabled:
          type: twig
          label: smartarget_smartarget_whatsapp_contact_us.ui.form.enabled
          options:
            template: SyliusUiBundle:Grid/Field:enabled.html.twig
      actions:
        main:
          create:
            type: create
            label: smartarget_smartarget_whatsapp_contact_us.ui.actions.create
        item:
          update:
            type: update
          delete:
            type: delete
      filters:
        phoneNumber:
          type: string
          label: smartarget_smartarget_whatsapp_contact_us.ui.form.phoneNumber
        smartargetUserId:
          type: string
          label: smartarget_smartarget_whatsapp_contact_us.ui.form.smartargetUserId
        enabled:
          type: boolean
          label: smartarget_smartarget_whatsapp_contact_us.ui.form.enabled
