services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Smartarget\SyliusSmartargetWhatsappContactUsPlugin\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Form/Type}'


  # Tip for Sylius 1.3:
  Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Repository\MessageRepository:
    autowire: false

  # Repository for autowiring
  Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Repository\MessageRepositoryInterface:
    alias: Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Repository\MessageRepository

  # Menu item in admin panel
  Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Listener\AdminMenuListener:
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

  # Message Forms
  smartarget_smartarget_whatsapp_contact_us.form.type.message:
    class: Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Form\Type\MessageType
    tags:
      - { name: form.type }
    arguments:
      - '%smartarget_smartarget_whatsapp_contact_us.model.message.class%'

  # Front
  smartarget_smartarget_whatsapp_contact_us.block_event_listener.layout.before_body:
    class: Smartarget\SyliusSmartargetWhatsappContactUsPlugin\Block\BlockEventListener
    arguments:
      $template: '@@SmartargetSyliusSmartargetWhatsappContactUsPlugin/message.html.twig'
      $channelContext: '@sylius.context.channel.composite'
      $localeContext: '@sylius.context.locale.composite'
      $customerContext: '@sylius.context.customer'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.before_body, method: onBlockEvent }
